[project]
name = "biz-dfch-llmops"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ronald Rink", email = "dfch@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
biz-dfch-llmops = "biz_dfch_llmops:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
